-- Minimal audit trail.
--
-- Attribution has to outlive the account that produced it: deactivating or
-- deleting a user must never erase what that user did. The actor reference is
-- therefore nullable and cleared on delete, while actor_label keeps a readable
-- identity denormalised inside the event.
--
-- target_type is constrained to the taxonomy this schema is expected to grow
-- into, so later phases can record memberships, revisions and builds without a
-- further migration.

CREATE TABLE audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  action VARCHAR(64) NOT NULL,
  outcome VARCHAR(16) NOT NULL DEFAULT 'success',
  actor_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
  actor_label VARCHAR(190) NOT NULL,
  target_type VARCHAR(32) NOT NULL,
  target_id VARCHAR(64),
  ip VARCHAR(45),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT audit_events_action_check CHECK (action <> ''),
  CONSTRAINT audit_events_actor_label_check CHECK (actor_label <> ''),
  CONSTRAINT audit_events_outcome_check CHECK (outcome IN ('success', 'failure')),
  CONSTRAINT audit_events_target_type_check CHECK (
    target_type IN ('system', 'user', 'session', 'project', 'membership', 'revision', 'build')
  ),
  CONSTRAINT audit_events_metadata_object_check CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX idx_audit_events_recent ON audit_events (occurred_at DESC, id DESC);
CREATE INDEX idx_audit_events_actor ON audit_events (actor_id, occurred_at DESC);
CREATE INDEX idx_audit_events_target ON audit_events (target_type, target_id, occurred_at DESC);
