-- Entity identifiers become UUIDv7 (RFC 9562).
--
-- One rule for every identifier, adopted while the schema is still small: a
-- 48-bit timestamp prefix keeps primary key inserts local in the B-tree instead
-- of scattering them the way version 4 does, and the uuid type costs 16 bytes
-- against the 32 plus header of the CHAR(32) it replaces.
--
-- audit_events.id deliberately stays a BIGINT identity: it is append-only,
-- never exposed in a URL and never referenced by another table, so the narrower
-- key is worth more there than uniformity.
--
-- Identifiers are generated by the application, never by a column default: a
-- project id is needed to build its storage path before the row is inserted.

-- Temporary generator, used only for the backfill below. It relies on functions
-- available since PostgreSQL 13 rather than the uuidv7() builtin added in 18, so
-- this migration does not raise the required server version. Existing rows get a
-- truthful id: the embedded timestamp is the row's own creation time, so
-- backfilled ids sort in creation order exactly like generated ones.
CREATE FUNCTION iris_uuidv7_at(ts timestamptz) RETURNS uuid
LANGUAGE sql VOLATILE AS $$
  WITH raw AS (
    SELECT substring(int8send((floor(extract(epoch FROM ts) * 1000))::bigint) FROM 3 FOR 6)
           || substring(uuid_send(gen_random_uuid()) FROM 7 FOR 10) AS b
  ), versioned AS (
    SELECT set_byte(b, 6, (get_byte(b, 6) & 15) | 112) AS b FROM raw
  )
  SELECT encode(set_byte(b, 8, (get_byte(b, 8) & 63) | 128), 'hex')::uuid FROM versioned;
$$;

ALTER TABLE users ADD COLUMN uuid_id UUID;
ALTER TABLE projects ADD COLUMN uuid_id UUID, ADD COLUMN uuid_user_id UUID;
ALTER TABLE audit_events ADD COLUMN uuid_actor_id UUID;

UPDATE users SET uuid_id = iris_uuidv7_at(created_at);
UPDATE projects SET uuid_id = iris_uuidv7_at(created_at);
UPDATE projects p SET uuid_user_id = u.uuid_id FROM users u WHERE u.id = p.user_id;
UPDATE audit_events a SET uuid_actor_id = u.uuid_id FROM users u WHERE u.id = a.actor_id;

-- audit_events.target_id holds identifiers as text, so it has to follow the
-- rewrite or the trail would point at ids that no longer exist. Events naming an
-- already deleted entity cannot be translated and keep their historical value.
UPDATE audit_events a SET target_id = u.uuid_id::text
FROM users u WHERE a.target_type = 'user' AND a.target_id = u.id::text;
UPDATE audit_events a SET target_id = p.uuid_id::text
FROM projects p WHERE a.target_type = 'project' AND a.target_id = p.id;

-- The storage directory is named after the project id, so it needs renaming too.
-- Recording the current location in legacy_storage_path hands that move to the
-- relocation step introduced by 002; COALESCE keeps an older pending source if
-- one is still recorded there.
UPDATE projects
SET legacy_storage_path = COALESCE(legacy_storage_path, storage_path),
    storage_path = 'projects/' || uuid_id;

-- Dropping a column drops the constraints and indexes that depend on it, so the
-- referencing columns go first and users.id last.
ALTER TABLE projects DROP COLUMN user_id;
ALTER TABLE audit_events DROP COLUMN actor_id;
ALTER TABLE projects DROP COLUMN id;
ALTER TABLE users DROP COLUMN id;

ALTER TABLE users RENAME COLUMN uuid_id TO id;
ALTER TABLE users ALTER COLUMN id SET NOT NULL;
ALTER TABLE users ADD PRIMARY KEY (id);

ALTER TABLE projects RENAME COLUMN uuid_id TO id;
ALTER TABLE projects RENAME COLUMN uuid_user_id TO user_id;
ALTER TABLE projects ALTER COLUMN id SET NOT NULL;
ALTER TABLE projects ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE projects ADD PRIMARY KEY (id);
ALTER TABLE projects ADD CONSTRAINT projects_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE audit_events RENAME COLUMN uuid_actor_id TO actor_id;
ALTER TABLE audit_events ADD CONSTRAINT audit_events_actor_id_fkey
  FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE SET NULL;

CREATE INDEX idx_projects_user_updated ON projects (user_id, updated_at DESC);
CREATE INDEX idx_audit_events_actor ON audit_events (actor_id, occurred_at DESC);

DROP FUNCTION iris_uuidv7_at(timestamptz);
