-- Stable, server-owned identity for project source files.
--
-- Until now a file was identified only by its path inside project.json, so a
-- rename was indistinguishable from delete-plus-create and any history keyed on
-- a file would break the first time it was renamed. This ledger gives every
-- source file a UUIDv7 that survives renames and moves, which is the anchor the
-- file-revision work (phase 3) will reference.
--
-- Folders are intentionally not tracked: they carry no content and inherit their
-- path from their files. Generated output and font assets are managed by their
-- own subsystems and are excluded from the ledger.
--
-- Identity continuity is preserved across a rename by updating `path` on the
-- same row. A removed file is soft-deleted, never hard-deleted, so a future
-- revision history of a deleted file still resolves.
--
-- `client_ref` records the manifest node id as first seen. The browser keeps a
-- node's id stable across a rename but only adopts the server's UUIDv7 after a
-- reload, so this column correlates a file across the saves of a single session
-- before that convergence. Ids are generated by the application, never here.

CREATE TABLE project_files (
  id UUID PRIMARY KEY,
  project_id UUID NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  client_ref TEXT,
  path TEXT NOT NULL,
  kind VARCHAR(16),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT project_files_path_check CHECK (
    path <> '' AND path !~ '^/' AND path NOT LIKE '%..%'
  )
);

-- A path identifies at most one live file within a project; soft-deleted rows
-- keep their old path without colliding.
CREATE UNIQUE INDEX uq_project_files_live_path
  ON project_files (project_id, path) WHERE deleted_at IS NULL;
CREATE INDEX idx_project_files_project_live
  ON project_files (project_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_project_files_client_ref
  ON project_files (project_id, client_ref) WHERE deleted_at IS NULL;
