% Iris final-page collector, format 1. Loaded only in this compiler process.
% The ordinary PS output function always runs, including on collector failure.
#(catch #t
  (lambda ()
    (use-modules (lily framework-ps) (lily output-ps))
    (let* ((framework (resolve-module '(lily framework-ps)))
           (original (module-ref framework 'output-stencils))
           (entries 0) (bytes 0) (visits 0) (elapsed 0) (failed #f)
           (identity '(1 0 0 1 0 0)))
      (define (multiply m n)
        (let ((a (list-ref m 0)) (b (list-ref m 1))
              (c (list-ref m 2)) (d (list-ref m 3))
              (e (list-ref m 4)) (f (list-ref m 5))
              (g (list-ref n 0)) (h (list-ref n 1))
              (i (list-ref n 2)) (j (list-ref n 3))
              (k (list-ref n 4)) (l (list-ref n 5)))
          (list (+ (* a g) (* c h)) (+ (* b g) (* d h))
                (+ (* a i) (* c j)) (+ (* b i) (* d j))
                (+ (* a k) (* c l) e) (+ (* b k) (* d l) f))))
      (define (point m x y)
        (cons (+ (* (list-ref m 0) x) (* (list-ref m 2) y) (list-ref m 4))
              (+ (* (list-ref m 1) x) (* (list-ref m 3) y) (list-ref m 5))))
      (module-set! framework 'output-stencils
        (lambda (basename stencils header paper formats)
          (if (and (not failed) (member "pdf" formats) (eq? (ly:get-option 'backend) 'ps))
            (let ((port #f) (start (get-internal-real-time)))
              (define (check)
                (set! visits (1+ visits))
                (if (or failed (> visits 2000000) (> entries 200000)
                        (> (+ elapsed (- (get-internal-real-time) start))
                           (* 5 internal-time-units-per-second)))
                  (throw 'iris-map-budget)))
              (define (emit str)
                (check)
                (set! bytes (+ bytes (string-length str)))
                (if (> bytes (- 16777216 32)) (throw 'iris-map-budget))
                (display str port))
              (catch #t
                (lambda ()
                  (set! port (open-output-file (string-append basename ".iris-map.tsv")))
                  (emit "IRIS-LILYPOND\t1\n")
                  (let* ((ordinal 0)
                         (scale (/ (ly:output-def-lookup paper 'output-scale) (ly:bp 1)))
                         (paper-width (ly:output-def-lookup paper 'paper-width))
                         (paper-height (ly:output-def-lookup paper 'paper-height))
                         (landscape? (eq? (ly:output-def-lookup paper 'landscape) #t))
                         ;; Match framework-ps dump-page's physical 90-degree turn.
                         (page-matrix (if landscape? (list 0 1 -1 0 0 (- paper-width)) identity)))
                    (for-each
                      (lambda (stencil)
                        (check)
                        (set! ordinal (1+ ordinal))
                        (set! entries (1+ entries))
                        (emit (format #f "P\t~a\t~a\t~a\n" ordinal
                          (* scale (if landscape? paper-height paper-width))
                          (* scale (if landscape? paper-width paper-height))))
                        (let ((matrix page-matrix) (stack '()))
                          (define (push transform)
                            (if (>= (length stack) 256) (throw 'iris-map-budget))
                            (set! stack (cons matrix stack))
                            (set! matrix (multiply matrix transform)) "")
                          (define (pop . args)
                            (if (null? stack) (throw 'iris-map-transform))
                            (set! matrix (car stack)) (set! stack (cdr stack)) "")
                          (define (rotate angle x y)
                            (let* ((r (* angle (/ (acos -1) 180))) (c (cos r)) (s (sin r)))
                              (push (list c s (- s) c
                                (+ x (- (* c x)) (* s y))
                                (- y (* s x) (* c y))))))
                          (define (collect offset grob)
                            (let* ((cause (ly:grob-property grob 'cause))
                                   (origin (and (ly:stream-event? cause)
                                                (ly:event-property cause 'origin))))
                              (if (ly:input-location? origin)
                                (let ((location (ly:input-file-line-char-column origin))
                                      (x (ly:grob-extent grob grob X))
                                      (y (ly:grob-extent grob grob Y)))
                                  (if (and (> (interval-length x) 0) (> (interval-length y) 0))
                                    (let* ((points (map (lambda (p)
                                                   (point matrix (+ (car offset) (car p))
                                                                 (+ (cdr offset) (cdr p))))
                                                 (list (cons (car x) (car y)) (cons (car x) (cdr y))
                                                       (cons (cdr x) (car y)) (cons (cdr x) (cdr y)))))
                                           (xs (map car points)) (ys (map cdr points))
                                           (left (* scale (apply min xs)))
                                           (top (* (- scale) (apply max ys)))
                                           (width (* scale (- (apply max xs) (apply min xs))))
                                           (height (* scale (- (apply max ys) (apply min ys)))))
                                      (set! entries (1+ entries))
                                      (emit (format #f "G\t~a\t~a\t~a\t~a\t~a\t~a\t~a\t~a\t~a\n"
                                        ordinal (ly:string-percent-encode (car location))
                                        (cadr location) (caddr location) (cadddr location)
                                        left top width height)))))))
                            "")
                          (let* ((handlers `((grob-cause . ,collect)
                                             (setscale . ,(lambda (x y) (push (list x 0 0 y 0 0))))
                                             (resetscale . ,pop) (setrotation . ,rotate) (resetrotation . ,pop)))
                                 (dispatch (map (lambda (entry)
                                             (let ((handler (assoc-get (car entry) handlers (lambda args ""))))
                                               (cons (car entry) (lambda args (check) (apply handler args)))))
                                           stencil-dispatch-alist))
                                 (sink (open-output-string))
                                 (outputter (ly:make-paper-outputter sink dispatch)))
                            (dynamic-wind (lambda () #t)
                              (lambda () (ly:outputter-dump-stencil outputter stencil))
                              (lambda () (ly:outputter-close outputter))))))
                      stencils)))
                (lambda (key . args)
                  (set! failed #t)
                  (if port (catch #t
                    (lambda () (display (if (eq? key 'iris-map-budget) "E\tbudget\n" "E\tcollector\n") port))
                    (lambda args #f)))))
              (set! elapsed (+ elapsed (- (get-internal-real-time) start)))
              (if port (catch #t (lambda () (close-port port)) (lambda args #f)))))
          (original basename stencils header paper formats)))))
  (lambda args #f))
