-- Current application schema. initializeSchema owns the transaction and version
-- marker. Incompatible definition changes require a CURRENT_SCHEMA_VERSION bump.
-- Entity UUIDs are generated by the application before persistence.

CREATE TABLE users (
  id UUID PRIMARY KEY,
  username VARCHAR(80) NOT NULL,
  email VARCHAR(190) NOT NULL,
  display_name VARCHAR(190) NOT NULL,
  system_role TEXT NOT NULL DEFAULT 'regular',
  password_hash VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  auth_source VARCHAR(16) NOT NULL DEFAULT 'local',
  oidc_issuer TEXT,
  oidc_subject TEXT,
  disabled_at TIMESTAMPTZ,
  last_login_at TIMESTAMPTZ,
  password_change_required BOOLEAN NOT NULL DEFAULT FALSE,
  oidc_link_pending BOOLEAN NOT NULL DEFAULT FALSE,
  oidc_linked_at TIMESTAMPTZ,
  session_version INTEGER NOT NULL DEFAULT 0 CHECK (session_version >= 0),
  CONSTRAINT users_system_role_check CHECK (system_role IN ('admin', 'regular', 'external')),
  CONSTRAINT users_status_check CHECK (status IN ('active', 'disabled', 'pending')),
  CONSTRAINT users_auth_source_check CHECK (auth_source IN ('local', 'oidc'))
);

CREATE UNIQUE INDEX uq_users_username_ci ON users (LOWER(username));
CREATE UNIQUE INDEX uq_users_email_ci ON users (LOWER(email));
CREATE UNIQUE INDEX uq_users_oidc_identity ON users (oidc_issuer, oidc_subject)
  WHERE oidc_issuer IS NOT NULL AND oidc_subject IS NOT NULL;

CREATE TABLE projects (
  id UUID PRIMARY KEY,
  created_by UUID REFERENCES users (id) ON DELETE SET NULL,
  name VARCHAR(160) NOT NULL,
  storage_path VARCHAR(512) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revision INTEGER NOT NULL DEFAULT 0 CHECK (revision >= 0),
  -- NULL follows the instance default; checks bound direct SQL writers too.
  build_keep INTEGER,
  build_days INTEGER,
  version_keep INTEGER,
  version_days INTEGER,
  CONSTRAINT projects_storage_path_relative CHECK (
    storage_path <> '' AND storage_path !~ '^(/|[A-Za-z]:[\\/])' AND storage_path NOT LIKE '%..%'
  ),
  CONSTRAINT projects_storage_path_canonical CHECK (storage_path = 'projects/' || id::text),
  CONSTRAINT projects_build_keep_check CHECK (build_keep IS NULL OR (build_keep >= 3 AND build_keep <= 200)),
  CONSTRAINT projects_build_days_check CHECK (build_days IS NULL OR (build_days >= 1 AND build_days <= 365)),
  CONSTRAINT projects_version_keep_check CHECK (version_keep IS NULL OR (version_keep >= 10 AND version_keep <= 1000)),
  CONSTRAINT projects_version_days_check CHECK (version_days IS NULL OR (version_days >= 7 AND version_days <= 1095))
);

CREATE INDEX idx_projects_created_by ON projects (created_by);

-- Attribution survives deletion of the account it describes.
CREATE TABLE audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  action VARCHAR(64) NOT NULL,
  outcome VARCHAR(16) NOT NULL DEFAULT 'success',
  actor_id UUID REFERENCES users (id) ON DELETE SET NULL,
  actor_label VARCHAR(190) NOT NULL,
  target_type VARCHAR(32) NOT NULL,
  target_id VARCHAR(64),
  ip VARCHAR(45),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT audit_events_action_check CHECK (action <> ''),
  CONSTRAINT audit_events_actor_label_check CHECK (actor_label <> ''),
  CONSTRAINT audit_events_outcome_check CHECK (outcome IN ('success', 'failure')),
  CONSTRAINT audit_events_target_type_check CHECK (
    target_type IN ('system', 'user', 'session', 'project', 'membership', 'revision', 'build')
  ),
  CONSTRAINT audit_events_metadata_object_check CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT audit_events_metadata_scalars_check CHECK (
    NOT jsonb_path_exists(
      metadata,
      'strict $.* ? (@.type() == "object" || @.type() == "array" || @.type() == "null")'
    )
  ),
  CONSTRAINT audit_events_metadata_size_check CHECK (octet_length(metadata::text) <= 8192)
);

CREATE INDEX idx_audit_events_recent ON audit_events (occurred_at DESC, id DESC);
CREATE INDEX idx_audit_events_actor ON audit_events (actor_id, occurred_at DESC);
CREATE INDEX idx_audit_events_target ON audit_events (target_type, target_id, occurred_at DESC);

-- Stable file identity survives renames and soft deletion. client_ref correlates
-- browser saves until the browser adopts the server-owned UUID on reload.
CREATE TABLE project_files (
  id UUID PRIMARY KEY,
  project_id UUID NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  client_ref TEXT,
  path TEXT NOT NULL,
  kind VARCHAR(16),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT project_files_path_check CHECK (path <> '' AND path !~ '^/' AND path NOT LIKE '%..%'),
  CONSTRAINT project_files_id_project_unique UNIQUE (id, project_id)
);

CREATE UNIQUE INDEX uq_project_files_live_path ON project_files (project_id, path) WHERE deleted_at IS NULL;
CREATE INDEX idx_project_files_project_live ON project_files (project_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_project_files_client_ref ON project_files (project_id, client_ref) WHERE deleted_at IS NULL;

CREATE TABLE document_versions (
  id UUID PRIMARY KEY,
  file_id UUID NOT NULL REFERENCES project_files (id) ON DELETE CASCADE,
  parent_version_id UUID REFERENCES document_versions (id) ON DELETE SET NULL,
  author_id UUID REFERENCES users (id) ON DELETE SET NULL,
  author_label VARCHAR(190) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reason VARCHAR(16) NOT NULL,
  content_hash CHAR(64) NOT NULL,
  content TEXT NOT NULL,
  size INTEGER NOT NULL,
  CONSTRAINT document_versions_reason_check CHECK (reason IN ('manual', 'compile', 'rollback', 'initial', 'realtime')),
  CONSTRAINT document_versions_author_label_check CHECK (author_label <> ''),
  CONSTRAINT document_versions_size_check CHECK (size >= 0),
  CONSTRAINT document_versions_id_file_unique UNIQUE (id, file_id)
);

CREATE INDEX idx_document_versions_file ON document_versions (file_id, created_at DESC, id DESC);

-- Membership is the authority for project access; created_by is provenance.
CREATE TABLE project_members (
  project_id UUID NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role VARCHAR(16) NOT NULL,
  invited_by UUID REFERENCES users (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (project_id, user_id),
  CONSTRAINT project_members_role_check CHECK (role IN ('owner', 'editor', 'viewer'))
);

CREATE INDEX idx_project_members_user ON project_members (user_id, created_at DESC);

CREATE TABLE build_outputs (
  id UUID PRIMARY KEY,
  project_id UUID NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  source_file_id UUID NOT NULL,
  source_revision_id UUID,
  source_content_hash CHAR(64) NOT NULL,
  created_by UUID REFERENCES users (id) ON DELETE SET NULL,
  created_by_label VARCHAR(190) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ,
  status VARCHAR(16) NOT NULL DEFAULT 'running',
  project_type VARCHAR(16) NOT NULL,
  compiler VARCHAR(32) NOT NULL,
  format VARCHAR(16) NOT NULL,
  main_path TEXT NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  storage_path TEXT,
  size BIGINT NOT NULL DEFAULT 0,
  content_hash CHAR(64),
  artifact_count INTEGER NOT NULL DEFAULT 0,
  duration_ms INTEGER,
  exit_code INTEGER,
  signal VARCHAR(32),
  timed_out BOOLEAN NOT NULL DEFAULT FALSE,
  log TEXT NOT NULL DEFAULT '',
  warnings JSONB NOT NULL DEFAULT '[]'::jsonb,
  errors JSONB NOT NULL DEFAULT '[]'::jsonb,
  diagnostics_version INTEGER,
  CONSTRAINT build_outputs_status_check CHECK (status IN ('running', 'succeeded', 'failed')),
  CONSTRAINT build_outputs_project_type_check CHECK (project_type IN ('latex', 'lilypond')),
  CONSTRAINT build_outputs_format_check CHECK (format IN ('pdf', 'png', 'svg', 'ps', 'eps')),
  CONSTRAINT build_outputs_creator_label_check CHECK (created_by_label <> ''),
  CONSTRAINT build_outputs_main_path_check CHECK (
    main_path <> '' AND main_path !~ '(^/|(^|/)\.\.(/|$)|\\)'
  ),
  CONSTRAINT build_outputs_display_name_check CHECK (display_name <> ''),
  CONSTRAINT build_outputs_size_check CHECK (size >= 0),
  CONSTRAINT build_outputs_artifact_count_check CHECK (artifact_count >= 0),
  CONSTRAINT build_outputs_duration_check CHECK (duration_ms IS NULL OR duration_ms >= 0),
  CONSTRAINT build_outputs_json_check CHECK (jsonb_typeof(warnings) = 'array' AND jsonb_typeof(errors) = 'array'),
  CONSTRAINT build_outputs_source_file_fkey FOREIGN KEY (source_file_id, project_id)
    REFERENCES project_files (id, project_id) ON DELETE CASCADE,
  CONSTRAINT build_outputs_source_revision_fkey FOREIGN KEY (source_revision_id, source_file_id)
    REFERENCES document_versions (id, file_id) ON DELETE SET NULL (source_revision_id),
  CONSTRAINT build_outputs_lifecycle_check CHECK (
    (status = 'running' AND completed_at IS NULL AND storage_path IS NULL AND artifact_count = 0 AND size = 0 AND content_hash IS NULL)
    OR
    (status = 'succeeded' AND completed_at IS NOT NULL AND storage_path = 'output/' || id::text AND artifact_count > 0 AND content_hash IS NOT NULL)
    OR
    (status = 'failed' AND completed_at IS NOT NULL AND storage_path IS NULL AND artifact_count = 0 AND size = 0 AND content_hash IS NULL)
  )
);

CREATE TABLE build_artifacts (
  id UUID PRIMARY KEY,
  build_id UUID NOT NULL REFERENCES build_outputs (id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  storage_path TEXT NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  size BIGINT NOT NULL,
  content_hash CHAR(64) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT build_artifacts_name_check CHECK (name <> '' AND name NOT IN ('.', '..') AND name !~ '[/\\]'),
  CONSTRAINT build_artifacts_path_check CHECK (
    storage_path <> '' AND storage_path !~ '(^/|(^|/)\.\.(/|$)|\\)'
  ),
  CONSTRAINT build_artifacts_mime_check CHECK (mime_type <> ''),
  CONSTRAINT build_artifacts_size_check CHECK (size >= 0),
  UNIQUE (build_id, name),
  UNIQUE (build_id, storage_path)
);

CREATE INDEX idx_build_outputs_project ON build_outputs (project_id, created_at DESC, id DESC);
CREATE INDEX idx_build_outputs_source_revision ON build_outputs (source_revision_id) WHERE source_revision_id IS NOT NULL;
CREATE INDEX idx_build_outputs_creator ON build_outputs (created_by, created_at DESC) WHERE created_by IS NOT NULL;
CREATE INDEX idx_build_artifacts_build ON build_artifacts (build_id, name);
CREATE INDEX idx_build_outputs_prunable ON build_outputs (created_at) WHERE status <> 'running';
CREATE INDEX idx_build_outputs_running ON build_outputs (created_at) WHERE status = 'running';

-- No foreign keys: retry authority must outlive both the project and its owners.
-- Cleanup paths are derived by the server, never stored in a receipt.
CREATE TABLE project_deletions (
  project_id UUID PRIMARY KEY,
  owner_ids UUID[] NOT NULL,
  state TEXT NOT NULL CHECK (state IN ('prepared', 'cleanup_ready', 'complete')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ,
  CHECK ((state = 'complete') = (completed_at IS NOT NULL)),
  CHECK (completed_at >= created_at)
);
